### ISSUE TITLE
display() - mapbox hover "help" doesn't display non-numeric data

### ISSUE THREAD

**Issue by ptitzler** [pixiedust/pixiedust#203]
0.86 (not data set specific)

```
import pixiedust
df=pixiedust.SampleData(2)
display(df)
```

* Select `Map` chart type
* As _keys_ select `Longitude` and `Latitude`
* As _value_ select a numeric field (e.g. `price`) and a non-numeric field (e.g. `name`)
* Choose `mapbox` as _renderer_
* Hover over a marker

### Expected behavior

The hover help/tool tip displays the values for the selected numeric field (e.g. `price`) and non-numeric field (e.g. `name`).

### Actual behavior

The hover help/tool tip displays the values for the selected numeric field (e.g. `price`) only.

**Comment by rajrsingh** [comment]
Requires a re-work of the options for mapping. Probable fix is adding a new option for mapping renderers that allows user to specify fields only for pop-up display.

**Comment by vabarbosa** [comment]
@DTAIEB the problem here is the default implementation of `baseChartDisplay.getValueFields()` removes all non-numeric valueFields columns. map renderers (or any renderer which allows non numeric valueFields) should either use
- a different implementation of `getValueFields` (which does not remove non-numeric columns if aggregation is not supported)
or
- place non-numeric columns into the 'preserveCols' field

**Comment by vabarbosa** [comment]
@glynnbird we have this, if you want to try another

**Comment by glynnbird** [comment]
Slightly modified instructions to reproduce:

```python
import pixiedust
df=pixiedust.sampleData(2)
display(df)
```

- Select Map chart type
- As keys select Longitude and Latitude
- As value select a numeric field (e.g. price) and a non-numeric field (e.g. name)
- Choose mapbox as renderer
- Hover over a marker

**Comment by rajrsingh** [comment]
fixed in https://github.com/ibm-watson-data-lab/pixiedust/tree/mapbox-v2
